# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ArtistaFormWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(499, 411)
        MainWindow.setStyleSheet("font: 12pt \"Century Gothic\";")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(150, 20, 211, 21))
        self.label.setObjectName("label")
        self.formLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.formLayoutWidget.setGeometry(QtCore.QRect(70, 60, 371, 264))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.tituloDeLaCancionLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.tituloDeLaCancionLabel.setObjectName("tituloDeLaCancionLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.tituloDeLaCancionLabel)
        self.nombreArtistaLineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.nombreArtistaLineEdit.setObjectName("nombreArtistaLineEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.nombreArtistaLineEdit)
        self.seudonimoLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.seudonimoLabel.setObjectName("seudonimoLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.seudonimoLabel)
        self.seudonimoLineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.seudonimoLineEdit.setObjectName("seudonimoLineEdit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.seudonimoLineEdit)
        self.nacimientoLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.nacimientoLabel.setObjectName("nacimientoLabel")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.nacimientoLabel)
        self.nacimientoLineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.nacimientoLineEdit.setObjectName("nacimientoLineEdit")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.nacimientoLineEdit)
        self.nacionalidadLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.nacionalidadLabel.setObjectName("nacionalidadLabel")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.nacionalidadLabel)
        self.nacionalidadLineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.nacionalidadLineEdit.setObjectName("nacionalidadLineEdit")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.nacionalidadLineEdit)
        self.generoLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.generoLabel.setObjectName("generoLabel")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.generoLabel)
        self.genComboBox = QtWidgets.QComboBox(self.formLayoutWidget)
        self.genComboBox.setObjectName("genComboBox")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.genComboBox)
        self.addArtistaBtn = QtWidgets.QPushButton(self.formLayoutWidget)
        self.addArtistaBtn.setObjectName("addArtistaBtn")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.addArtistaBtn)
        self.clearArtistaFormBtn = QtWidgets.QPushButton(self.formLayoutWidget)
        self.clearArtistaFormBtn.setObjectName("clearArtistaFormBtn")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.clearArtistaFormBtn)
        self.sencillosLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.sencillosLabel.setObjectName("sencillosLabel")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.sencillosLabel)
        self.sencillosLineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.sencillosLineEdit.setObjectName("sencillosLineEdit")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.sencillosLineEdit)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 499, 27))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-family:\'Comic Sans\'; font-size:16pt; font-weight:600;\">Añadir artista</span></p></body></html>"))
        self.tituloDeLaCancionLabel.setText(_translate("MainWindow", "Nombre del artista"))
        self.seudonimoLabel.setText(_translate("MainWindow", "Seudonimo"))
        self.nacimientoLabel.setText(_translate("MainWindow", "Nacimiento"))
        self.nacionalidadLabel.setText(_translate("MainWindow", "Nacionalidad"))
        self.generoLabel.setText(_translate("MainWindow", "Genero"))
        self.addArtistaBtn.setText(_translate("MainWindow", "Agregar"))
        self.clearArtistaFormBtn.setText(_translate("MainWindow", "Limpiar"))
        self.sencillosLabel.setText(_translate("MainWindow", "Sencillos"))
