# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DetallesWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(885, 623)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(20, 10, 826, 551))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.songTitleLabel = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.songTitleLabel.setStyleSheet("font: 24pt \"Century Gothic\";")
        self.songTitleLabel.setObjectName("songTitleLabel")
        self.verticalLayout_3.addWidget(self.songTitleLabel)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.letraLabel = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.letraLabel.setStyleSheet("font: 24pt \"Century Gothic\";")
        self.letraLabel.setObjectName("letraLabel")
        self.verticalLayout.addWidget(self.letraLabel)
        self.letraTextEdit = QtWidgets.QTextEdit(self.verticalLayoutWidget_3)
        self.letraTextEdit.setObjectName("letraTextEdit")
        self.verticalLayout.addWidget(self.letraTextEdit)
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.subgenLabel = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.subgenLabel.setStyleSheet("font: 24pt \"Century Gothic\";")
        self.subgenLabel.setObjectName("subgenLabel")
        self.verticalLayout_2.addWidget(self.subgenLabel)
        self.historiaTextEdit = QtWidgets.QTextEdit(self.verticalLayoutWidget_3)
        self.historiaTextEdit.setObjectName("historiaTextEdit")
        self.verticalLayout_2.addWidget(self.historiaTextEdit)
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.label.setText("")
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.artistaLabel = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.artistaLabel.setStyleSheet("font: 24pt \"Century Gothic\";")
        self.artistaLabel.setObjectName("artistaLabel")
        self.verticalLayout_4.addWidget(self.artistaLabel)
        self.artistaTextEdit = QtWidgets.QTextEdit(self.verticalLayoutWidget_3)
        self.artistaTextEdit.setObjectName("artistaTextEdit")
        self.verticalLayout_4.addWidget(self.artistaTextEdit)
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.verticalLayout_4.addWidget(self.label_3)
        self.horizontalLayout.addLayout(self.verticalLayout_4)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.closeDetailsBtn = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.closeDetailsBtn.setObjectName("closeDetailsBtn")
        self.verticalLayout_3.addWidget(self.closeDetailsBtn)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 885, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.songTitleLabel.setText(_translate("MainWindow", "Título de la canción"))
        self.letraLabel.setText(_translate("MainWindow", "Letra"))
        self.subgenLabel.setText(_translate("MainWindow", "Subgénero"))
        self.artistaLabel.setText(_translate("MainWindow", "Artista"))
        self.closeDetailsBtn.setText(_translate("MainWindow", "Cerrar"))
