# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SubgeneroFormWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(558, 412)
        MainWindow.setStyleSheet("font: 12pt \"Century Gothic\";")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.formLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.formLayoutWidget.setGeometry(QtCore.QRect(60, 40, 441, 301))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.nombreLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.nombreLabel.setObjectName("nombreLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.nombreLabel)
        self.nombreLineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.nombreLineEdit.setObjectName("nombreLineEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.nombreLineEdit)
        self.letraLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.letraLabel.setObjectName("letraLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.letraLabel)
        self.textEdit = QtWidgets.QTextEdit(self.formLayoutWidget)
        self.textEdit.setObjectName("textEdit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.textEdit)
        self.addSubgenBtn = QtWidgets.QPushButton(self.formLayoutWidget)
        self.addSubgenBtn.setObjectName("addSubgenBtn")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.addSubgenBtn)
        self.clearSubgenFormBtn = QtWidgets.QPushButton(self.formLayoutWidget)
        self.clearSubgenFormBtn.setObjectName("clearSubgenFormBtn")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.clearSubgenFormBtn)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(180, 0, 211, 31))
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 558, 27))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.nombreLabel.setText(_translate("MainWindow", "Nombre"))
        self.letraLabel.setText(_translate("MainWindow", "Historia"))
        self.addSubgenBtn.setText(_translate("MainWindow", "Agregar"))
        self.clearSubgenFormBtn.setText(_translate("MainWindow", "Limpiar"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-family:\'Comic Sans\'; font-size:16pt; font-weight:600;\">Añadir subgénero</span></p></body></html>"))
